---
version: "3.6"

services:
  smartgic_rotation:
    container_name: smartgic_display_rotation
    hostname: display-rotation
    restart: unless-stopped
    image: smartgic/display-rotation:latest
    devices:
      - /dev/i2c-1
    environment:
      DISPLAY: :0
      THRESHOLD: 10
      AXIS: x
      MONITOR: HDMI-1
      POINTER: Logitech M325
      INTERVAL: 1
    volumes:
      - /sys:/sys:ro
